---
# tasks file for install_kubeless
- name: Create kubeless Namespace
  kubernetes.core.k8s:
    name: kubeless
    api_version: v1
    kind: Namespace
    state: present

- name: Apply kubeless resources.
  kubernetes.core.k8s:
    state: present
    template: ../files/kubeless.yaml
    namespace: kubeless