---
# tasks file for install_longhorn
- name: Create longhorn Namespace
  kubernetes.core.k8s:
    name: longhorn-system
    api_version: v1
    kind: Namespace
    state: present

- name: Add longhorn repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Install longhorn chart
  kubernetes.core.helm:
    name: longhorn
    state: present
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system

- name: Remove longhorn Namespace
  kubernetes.core.k8s:
    name: longhorn
    api_version: v1
    kind: Namespace
    state: absent