---
- name: Install libs
  pip:
    name: kubernetes
    state: present

- name: Install lib client
  pip:
    name: websocket-client
    state: present

- name: Create traefik Namespace
  kubernetes.core.k8s:
    name: traefik
    api_version: v1
    kind: Namespace
    state: present

- name: Add traefik repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"

- name: Install traefik chart
  kubernetes.core.helm:
    name: traefik
    state: present
    chart_ref: traefik/traefik
    release_namespace: traefik

- name: Traefik dashboard
  kubernetes.core.k8s:
    state: present
    template: '../templates/dashboard.j2'
    namespace: traefik
